#' @title DAVID Gene Ontology List Adder
#'
#' @description DAVID Gene Ontology Wrapper
#' @param davidWS A DAVIDWebService class object.
#' @param annotation_cat a string or vector of strings indicating which set of GO annotation terms to use
#' @param DE_data A data frame containing 3 columns ("Gene_ID", "LFC", and "padj").
#' @param list_name A string that will be used to identify the submitted list.
#' @param save_file logical. If TRUE, files generated by the DAVID GO analysis will be saved. This value is TRUE by default.
#' @param split_at a character at which strings will be split. If NULL (the default), strings will not be split.
#' @import org.Hs.eg.db
#' @import limma
#' @import stringi
#' @import RDAVIDWebService
#' @import openxlsx
#' @import AnnotationDbi
#' @export
#' @examples
#' add_gene_list(davidWS, DE_data, list_name)

add_gene_list <- function(davidWS, DE_data, list_name) {
  cNames <- colnames(DE_data)
  if (cNames[1] != "Gene_ID" | cNames[2] != "LFC" | cNames[3] != "padj") {
    return(print("Error: columns must be Gene_ID, LFC, and padj"))
  }

  filteredData <- subset(
    DE_data,
    DE_data$padj <= 0.05 & abs(DE_data$LFC) >= 1 & !grepl("ENSPANG", DE_data$Gene_ID)
  )
  ensemblIDs <- mapIds(
    org.Hs.eg.db, filteredData$Gene_ID, keytype = "SYMBOL", column = "ENSEMBL"
  )
  addList(
    davidWS, ensemblIDs, idType = "ENSEMBL_GENE_ID",
    listName = list_name, listType = "Gene"
  )
}
