#' @title DAVID Gene Ontology Wrapper
#'
#' @description DAVID Gene Ontology Wrapper
#' @param davidWS A DAVIDWebService class object.
#' @param annotation_cat a string or vector of strings indicating which set of GO annotation terms to use
#' @param DE_data A data frame containing 3 columns ("Gene_ID", "LFC", and "padj").
#' @param list_name A string that will be used to identify the submitted list.
#' @param save_file logical. If TRUE, files generated by the DAVID GO analysis will be saved. This value is TRUE by default.
#' @param split_at a character at which strings will be split. If NULL (the default), strings will not be split.
#' @import org.Hs.eg.db
#' @import limma
#' @import stringi
#' @import RDAVIDWebService
#' @import openxlsx
#' @import AnnotationDbi
#' @import GOplot
#' @export
#' @examples
#' run_DAVID(davidWS, list_name)

run_DAVID <- function(davidWS, DE_data, list_name, save_file = TRUE) {
  # Make sure input is valid --------------------------------------------------
    if (nrow(DE_data) < 1) {
      print("Error: input has 0 rows", quote = FALSE)
      return(NULL)
    }

    cNames <- colnames(DE_data)
    if (cNames[1] != "Gene_ID" | cNames[2] != "LFC" | cNames[3] != "padj") {
      print("Error: input must have 3 columns (Gene_ID, LFC, and padj)")
      return(NULL)
    }

    if (!is.connected(david)) {
      print("Error: not connected to RDAVIDWebService", quote = FALSE)
      return(NULL)
    }


  # Check to see if gene list has been added ----------------------------------
    gene_lists <- getGeneListNames(davidWS)
    list_position <- 0

    if (length(getGeneListNames(davidWS)) > 0) {
      for (x in 1:length(gene_lists)) {
        if (gene_lists[x] == list_name) list_position <- x
      }
    }

    if (list_position == 0) {
      ensemblIDs <- mapIds(
        org.Hs.eg.db, DE_data$Gene_ID,
        keytype = "SYMBOL", column = "ENSEMBL"
      )
      addList(
        davidWS, ensemblIDs, idType = "ENSEMBL_GENE_ID",
        listName = list_name, listType = "Gene"
      )

      gene_lists <- getGeneListNames(davidWS)
    } else setCurrentGeneListPosition(davidWS, list_position)

    print("Running GO analysis on gene list:")
    print(gene_lists[getCurrentGeneListPosition(davidWS)])

  # Run GO analysis -----------------------------------------------------------
    setAnnotationCategories(davidWS, c("GOTERM_BP_ALL"))
    FA_chart <- getFunctionalAnnotationChart(davidWS)
    FA_sub <- subset(FA_chart, FA_chart$FDR <= 0.05)

    if (nrow(FA_sub) < 1) {
      print("No significant GO terms")
      data.frame()
    } else {
      gene_list <- data.frame(FA_sub$Genes)
      for (r in 1:nrow(gene_list)) {
        gene_names <- limma::strsplit2(gene_list[r, 1], ", ")[1, ]
        gene_names <- list(
          mapIds(
            org.Hs.eg.db, gene_names, keytype = "ENSEMBL", column = "SYMBOL"
          )
        )
        gene_names <- stri_join_list(gene_names, sep = ", ")
        gene_list[r, 1] <- gene_names
      }

      split_IDs <- limma::strsplit2(FA_sub$Term, "~")
      FA_sub <- data.frame(
        FA_sub$Category, split_IDs, FA_sub$Count, FA_sub$X.,
        gene_list, FA_sub$Fold.Enrichment, FA_sub$FDR
      )
      colnames(FA_sub) <- c(
        "Category", "ID", "Term", "Count", "Percent_of_input_list",
        "Genes", "Fold.Enrichment", "FDR"
      )

      terms_data <- data.frame(FA_sub[, c(1:3, 8, 6)])
      colnames(terms_data) <- c("category", "ID", "term", "adj_pval", "genes")

      genes_data <- data.frame(DE_data$Gene_ID, DE_data$LFC)
      colnames(genes_data) <- c("ID", "logFC")

      cd <- GOplot::circle_dat(terms_data, genes_data)

      zScores <- cd[, c(2, 8)]
      zScores <- zScores[!duplicated(zScores), ]
      zScores <- dplyr::left_join(FA_sub, zScores, by = "ID")
      zScores <- subset(zScores, abs(zScores$zscore) >= 2)

      file_name <- stri_join(list_name, " GO Terms.xlsx")
      wb <- createWorkbook(file_name)
      addWorksheet(wb, "Bio_Process")
      writeData(wb, "Bio_Process", zScores)
      saveWorkbook(wb, file_name, overwrite = TRUE)

      zScores
    }
}
